import { MenuType } from '../type';

export const menu: MenuType[] = [
	{
		id: 1,
		title: 'Main',
		hr: true,
		show: true,
		children: [
			{
				id: 1,
				name: 'Dashboard',
				icon: 'LayoutGrid',
				show: true,
				children: [
					{
						id: 1,
						name: 'Admin Dashboard',
						show: true,
						path: '/',
					},
					{
						id: 2,
						name: 'Sales Dashboard',
						show: true,
						path: '/sales-dashboard',
					},
				],
			},
		],
	},
	{
		id: 2,
		title: 'Inventory',
		hr: true,
		show: true,
		children: [
			{
				id: 14,
				name: 'Products',
				show: true,
				path: '/inventory/products',
				icon: 'BarChart2',
			},
			{
				id: 15,
				name: 'Create Products',
				show: true,
				path: '/inventory/create-products',
				icon: 'PlusCircle',
			},
			{
				id: 16,
				name: 'Expired Products',
				show: true,
				path: '/inventory/expired-products',
				icon: 'Clock',
			},
			{
				id: 17,
				name: 'Low Stocks',
				show: true,
				path: '/inventory/low-stocks',
				icon: 'AlertTriangle',
			},
			{
				id: 18,
				name: 'Category',
				show: true,
				path: '/inventory/category',
				icon: 'Grid',
			},
			{
				id: 19,
				name: 'Sub Category',
				show: true,
				path: '/inventory/sub-category',
				icon: 'List',
			},
			{
				id: 20,
				name: 'Brand',
				show: true,
				path: '/inventory/brand',
				icon: 'Anchor',
			},
			{
				id: 21,
				name: 'Units',
				show: true,
				path: '/inventory/units',
				icon: 'Ruler',
			},
			{
				id: 22,
				name: 'Variant Attributes',
				show: true,
				path: '/inventory/variant-attributes',
				icon: 'Layers',
			},
			{
				id: 23,
				name: 'Warranties',
				show: true,
				path: '/inventory/warranties',
				icon: 'Shield',
			},
			{
				id: 24,
				name: 'Print Barcode',
				show: true,
				path: '/inventory/print-barcode',
				icon: 'Printer',
			},
			{
				id: 25,
				name: 'Print QR Code',
				show: true,
				path: '/inventory/print-qr-code',
				icon: 'QrCode',
			},
		],
	},
	{
		id: 3,
		title: 'Stock',
		hr: true,
		show: true,
		children: [
			{
				id: 14,
				name: 'Manage Stock',
				show: true,
				path: '/stock/manage-stock',
				icon: 'PackageCheck',
			},
			{
				id: 15,
				name: 'Stock Adjustment',
				show: true,
				path: '/stock/stock-adjustment',
				icon: 'PackageOpen',
			},
			{
				id: 16,
				name: 'Stock Transfer',
				show: true,
				path: '/stock/stock-transfer',
				icon: 'Truck',
			},
		],
	},
	{
		id: 4,
		title: 'Sales',
		hr: true,
		show: true,
		children: [
			{
				id: 14,
				name: 'Sales',
				show: true,
				path: '/sales/sales',
				icon: 'ShoppingCart',
			},
			{
				id: 15,
				name: 'Invoices',
				show: true,
				path: '/sales/invoices',
				icon: 'BarChart2',
			},
			{
				id: 16,
				name: 'Sales Return',
				show: true,
				path: '/sales/sales-return',
				icon: 'GitPullRequestCreateArrow',
			},
			{
				id: 17,
				name: 'Quotation',
				show: true,
				path: '/sales/quotation',
				icon: 'BarChart2',
			},
			{ id: 18, name: 'POS', show: true, path: '/sales/pos', icon: 'BookLock' },
		],
	},
	{
		id: 5,
		title: 'Promo',
		hr: true,
		show: true,
		children: [
			{
				id: 18,
				name: 'Coupons',
				show: true,
				path: '/promo/coupons',
				icon: 'BarChart2',
			},
		],
	},
	{
		id: 6,
		title: 'Purchases',
		hr: true,
		show: true,
		children: [
			{
				id: 18,
				name: 'Purchases',
				show: true,
				path: '/purchases/purchases',
				icon: 'BarChart2',
			},
			{
				id: 19,
				name: 'Purchase Order',
				show: true,
				path: '/purchases/purchase-order',
				icon: 'BarChart2',
			},
			{
				id: 20,
				name: 'Purchase Return',
				show: true,
				path: '/purchases/purchase-return',
				icon: 'BarChart2',
			},
		],
	},
	{
		id: 7,
		title: 'Finance & Accounts',
		hr: true,
		show: true,
		children: [
			{
				id: 1,
				name: 'Expenses',
				icon: 'DollarSign',
				show: true,
				children: [
					{
						id: 1,
						name: 'Expenses',
						show: true,
						path: '/expenses',
						icon: 'DollarSign',
					},
					{
						id: 2,
						name: 'Expense Category',
						show: true,
						path: '/expense-category',
						icon: 'Archive',
					},
				],
			},
		],
	},
	{
		id: 8,
		title: 'Peoples',
		hr: true,
		show: true,
		children: [
			{
				id: 18,
				name: 'Customers',
				show: true,
				path: '/peoples/customers',
				icon: 'User',
			},
			{
				id: 19,
				name: 'Suppliers',
				show: true,
				path: '/peoples/suppliers',
				icon: 'Truck',
			},
			{
				id: 20,
				name: 'Stores',
				show: true,
				path: '/peoples/stores',
				icon: 'ShoppingBag',
			},
			{
				id: 21,
				name: 'Warehouses',
				show: true,
				path: '/peoples/warehouses',
				icon: 'Warehouse',
			},
		],
	},
	{
		id: 9,
		title: 'HRM',
		hr: true,
		show: true,
		children: [
			{
				id: 22,
				name: 'Employees',
				show: true,
				path: '/employees',
				icon: 'Users',
			},
		],
	},
	{
		id: 10,
		title: 'Reports',
		hr: true,
		show: true,
		children: [
			{
				id: 1,
				name: 'Reports & Analytics',
				icon: 'TrendingUp',
				show: true,
				children: [
					{
						id: 18,
						name: 'Sales Report',
						show: true,
						path: '/reports/sales',
						icon: 'TrendingUp',
					},
					{
						id: 19,
						name: 'Purchase Report',
						show: true,
						path: '/reports/purchase',
						icon: 'TrendingDown',
					},
					{
						id: 20,
						name: 'Inventory Report',
						show: true,
						path: '/reports/inventory',
						icon: 'Package',
					},
					{
						id: 21,
						name: 'Invoice Report',
						show: true,
						path: '/reports/invoice',
						icon: 'FileText',
					},
					{
						id: 22,
						name: 'Supplier Report',
						show: true,
						path: '/reports/supplier',
						icon: 'Users',
					},
					{
						id: 23,
						name: 'Customer Report',
						show: true,
						path: '/reports/customer',
						icon: 'User',
					},
					{
						id: 24,
						name: 'Expense Report',
						show: true,
						path: '/reports/expense',
						icon: 'DollarSign',
					},
					{
						id: 25,
						name: 'Income Report',
						show: true,
						path: '/reports/income',
						icon: 'DollarSign',
					},
					{
						id: 26,
						name: 'Tax Report',
						show: true,
						path: '/reports/tax',
						icon: 'Percent',
					},
					{
						id: 27,
						name: 'Profit & Loss',
						show: true,
						path: '/reports/profit-loss',
						icon: 'DollarSign',
					},
				],
			},
		],
	},

	{
		id: 11,
		title: 'User Management',
		hr: true,
		show: true,
		children: [
			{
				id: 28,
				name: 'Users',
				show: true,
				path: '/user-management/users',
				icon: 'Users',
			},
			{
				id: 29,
				name: 'Roles & Permissions',
				show: true,
				path: '/user-management/roles-permissions',
				icon: 'Key',
			},
			{
				id: 30,
				name: 'Delete Account Request',
				show: true,
				path: '/user-management/delete-account-request',
				icon: 'Trash',
			},
		],
	},
	{
		id: 12,
		title: 'Settings',
		hr: true,
		show: true,
		children: [
			{
				id: 31,
				name: 'General Settings',
				show: true,
				path: '/settings/general',
				icon: 'Settings',
			},
			{
				id: 32,
				name: 'Website Settings',
				show: true,
				path: '/settings/website',
				icon: 'Globe',
			},

			{
				id: 34,
				name: 'System Settings',
				show: true,
				path: '/settings/system',
				icon: 'Wrench',
			},
			{
				id: 35,
				name: 'Financial Settings',
				show: true,
				path: '/settings/financial',
				icon: 'DollarSign',
			},
			{
				id: 36,
				name: 'Other Settings',
				show: true,
				path: '/settings/other',
				icon: 'SlidersHorizontal',
			},
			{ id: 37, name: 'Logout', show: true, path: '/logout', icon: 'LogOut' },
		],
	},
	{
		id: 13,
		title: 'Help',
		hr: true,
		show: true,
		children: [
			{
				id: 38,
				name: 'Documentation',
				show: true,
				path: '/help/documentation',
				icon: 'Book',
			},
		],
	},
];

/*
 this is dummy data for save can be helpful next time we need to use this
export const menu: MenuType[] = [
	{
		id: 1,
		title: 'Main',
		hr: true,
		show: true,
		children: [
			{
				id: 1,
				name: 'Dashboard',
				icon: 'LayoutGrid',
				children: [
					{
						id: 1,
						name: 'Admin Dashboard',
						show: true,path: '/',
					},
					{
						id: 2,
						name: 'Sales Dashboard',
						show: true,path: '/',
					},
				],
			},
			{
				id: 2,
				name: 'Category',
				show: true,path: '/category',
				icon: 'ShoppingCart',
			},
		],
	},
	{
		id: 1,
		title: 'Inventory',
		hr: true,
		show: true,
		children: [
			{
				id: 1,
				name: 'Products',
				show: true,path: '/',
				icon: 'Home',
				children: [
					{
						id: 1,
						name: 'Admin  2 Dashboard',
						show: true,path: '/',
					},
					{
						id: 2,
						name: 'Sales 2 Dashboard',
						show: true,path: '/',
					},
				],
			},
			{
				id: 2,
				name: 'Dashboard 2',
				show: true,path: '/',
				icon: 'Home',
				children: [
					{
						id: 1,
						name: 'Admin  2 Dashboard',
						show: true,path: '/',
						icon: 'Home',
					},
					{
						id: 2,
						name: 'Sales 2 Dashboard',
						show: true,path: '/',
						icon: 'Home',
					},
				],
			},
			{
				id: 6,
				name: 'Category',
				show: true,path: '/system/category',
				icon: 'LineChart',
			},
			
		],
	},
];

*/
